apiVersion: v1
kind: Service
metadata:
  name: k8s-sample-service
  namespace: k8s-sample
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    name: http
  selector:
    app: k8s-sample