apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: app
spec:
  host: "*"
  subsets:
  - name: v1 # ルールの名前
    labels:
      version: v1 # ラベルがついているPodへトラフィックを流す
  - name: v2
    labels:
      version: v2
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL